### PR TITLE
Cosmopolitan Patches

### PR DESCRIPTION
**Pull request by lmangani**
### Cosmocc

Various experimental (as in ugly) patches to compile dhtd using cosmocc/cosmopolitan

### Limits 

- no background mode supported
- In Cosmopolitan, `AF_INET6` (and potentially other AF_* constants) are defined as `const int` variables, not as `integer constants`

### CODE REVIEW

**Comment by lmangani** [comment]
Apologies, this is just a WIP - reopening on fork instead.

**Comment by mwarning** [comment]
Anyway, thanks for the "heads up". I have never heard about Cosmopolitan. :-)

**Comment by lmangani** [comment]
Thank you for making DHTd! I absolutely love it and thought it would be a perfect example to try Cosmopolitan with. I have managed to build a portable dhtd binary but its a little crippled - it won't run in the background (for now)

**Comment by mwarning** [comment]
@lmangani hah, I don't even now what to use DHTd for. But it was fun.

**Comment by lmangani** [comment]
@mwarning fun for sure! I'm using DHTd as backend to create a decentralized database query layer in DuckDB  https://github.com/lmangani/duckdb-extension-dht

**Pull request closed without merging**
